# 阶段
stages:
    - lint
    - build
    - deploy
    # 缓存 node_modules 减少打包时间，默认会清除 node_modules 和 dist
cache:
    paths:
        - node_modules/

lint:
    stage: lint
    tags:
        - vue3
    script:
        - npm i --registry https://registry.npm.taobao.org
        - npm run lint

build-test:
    stage: build
    tags:
        - vue3
    only:
        - master
        - develop
    script:
        - npm i --registry https://registry.npm.taobao.org
        - npm run build-test
    artifacts:
        paths:
            - dist
        expire_in: 1 week

# 拉取项目，打包
build:
    stage: build # 阶段名称 对应，stages
    tags: # runner 标签(注册runner时设置的，可在 setting ->runner中查看)
        - vue3
    only:
        - master
        - develop
    script: # 脚本（执行的命令行）
        # - cd ${CI_PROJECT_DIR} # 拉取项目的根目录
        # - echo "install"${CI_PROJECT_DIR}
        # - npm install # 安装依赖
        # - npm run build # 运行构建命令
        # - echo "build Successfully"
        - npm i --registry https://registry.npm.taobao.org
        - npm run build
    artifacts: # 把 dist 的内容传递给下一个阶
        paths:
            - dist
        expire_in: 1 week
    when: manual #是否需要手动执行

deploy-test:
    stage: deploy # 阶段名称 对应，stages
    tags: # runner 标签(注册runner时设置的)
        - vue3
    only:
        - master
        - develop
    script: # 脚本（执行的命令行）
        - rsync -rav --delete dist/ /usr/local/nginx/html/lpf_demo/ # 把包完成，复制 dist 下的文件到对应的项目位置
        - echo "deploy-test Successfully"
    dependencies:
        - build-test

# # 部署
deploy:
    stage: deploy # 阶段名称 对应，stages
    tags: # runner 标签(注册runner时设置的)
        - vue3
    script: # 脚本（执行的命令行）
        - rsync -rav --delete dist/ /usr/local/nginx/html/lpf_demo/ # 把包完成，复制 dist 下的文件到对应的项目位置
        - echo "deploy Successfully"
    only:
        - master
        - develop
    dependencies: #依赖项更新
        - build
    when: manual
